database:
  uri: "postgresql://postgres:postgres@172.17.0.2/file_storage"
  track_modifications: false

minio:
  host: "172.17.0.2:9000"
  access_key: "ift_bigdata"
  secret_key: "minio_password"
  secure: False
  bucket_name: "pdf-reports"
