database:
  uri: "postgresql://postgres:postgres@8.134.166.116/file_storage"
  track_modifications: false

minio:
  host: "8.134.166.116:9000"
  access_key: "ift_bigdata"
  secret_key: "minio_password"
  secure: False
  bucket_name: "pdf-reports"