database:
  uri: "postgresql://postgres:postgres@172.17.0.2/file_storage"
  track_modifications: false

minio:
  host: "172.17.0.2:9000"
  access_key: "ift_bigdata"
  secret_key: "minio_password"
  secure: False
  bucket_name: "pdf-reports"

miniocw:
  container_name: miniocw              
  image: minio/minio
  networks:
      - iceberg_net                      
  environment:
      - MINIO_ROOT_USER=ift_bigdata       
      - MINIO_ROOT_PASSWORD=minio_password 
      - MINIO_DOMAIN=miniocw             
  ports:
      - 9001:9001
      - 9000:9000
  command: ["server", "/data", "--console-address", ":9001"]

# PostgreSQL
  postgres_db:
    container_name: postgres_db_cw        
    image: postgres:10.5                    
    environment:
      - POSTGRES_USER=postgres             
      - POSTGRES_PASSWORD=postgres         
      - PGUSER=postgres                   
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5439:5432'                       
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5      
